config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: 'polls#voter'

	resource :polls do
		get :voter
		post :save_response
		get :thanks
	end

	resources :responses do
		collection do
			get :fetch_data
		end
	end
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
	has_many :responses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
	enum question_type: [:radio, :checkbox, :dropdown]

	has_many :answers
	has_many :responses
end

app/models/response.rb
class Response < ApplicationRecord
	belongs_to :question
	belongs_to :answer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

	def voter
		@questions = Question.includes(:answers).all
	end

	def save_response
		pp params
		params.each do |param|
			Response.create(question_id: param[0], answer_id: param[1])
		end
		redirect_to thanks_polls_path
	end

	def thanks

	end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

	def index
		
	end

	def fetch_data
		questions = Question.includes(:responses,:answers).all
		all_responses = []
		questions.each do |question|
			resp = []
			question.answers.each do |c|
				response_count = question.responses.where(answer_id: c.id).count
				resp << [c.answer, response_count]
			end
			response =  { question: question, answer:  resp }
			all_responses << response
		end
		xx =  all_responses.map{ |x| [ x[:question].id, x[:question].question , x[:answer] ] }
		render json: { responses: xx}
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PublicOpinionSurveyor</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="page-content" style="background-image: url('/assets/wizard-v1.jpg')">
  <div class="wizard-v1-content">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/polls/thanks.html.erb
<div class="wizard-form thanks">
  <span> THANK YOU! </span>
  <section>
    <div class="inner">
      <div >
        <%= button_to "See Results", responses_path, :id => "open-contacts-dialog-btn",
                      :class => "btn btn-primary", :method => :get %>
      </div>
    </div>
  </section>
</div>

app/views/polls/voter.html.erb
<div class="wizard-form">
  <form class="form-register" id="form-register" action="#" method="post">
    <div id="form-total">
      <!-- SECTION 1 -->
      <% @questions.each_with_index do |question, index| %>
        <h2>
          <!-- <span class="step-icon"><i class="zmdi zmdi-account"></i></span> -->
          <span class="step-number"><%= index+1 %>. </span>
          <span class="step-text"><%= question.question %></span>
        </h2>
        <section>
          <div class="inner">
            <% if question.question_type == 'radio'  %>
              <% question.answers.each do |answer| %>
                <div class="form-row">
                  <%= radio_button_tag question.id, answer.id %>
                  <label for="username"><%= answer.answer %></label>
                </div>
              <% end %>
            <% else %>
              <%= select_tag question.id, options_for_select(question.answers.collect{ |u| [u.answer, u.id] }) %>
            <% end %>
          </div>
        </section>
      <% end %>
    </div>
    <section>
      <div class="inner">
        <div class="form-row">
          <button class="btn btn-primary" id="save-response"> Save </button>
        </div>
      </div>
    </section>
  </form>
</div>

app/views/responses/index.html.erb
<div id="response-container">

  <div id="container-one" class='container' style="width:100%; height:400px;"></div>

  <div id="container-two" class='container' style="width:100%; height:400px;"></div>

  <div id="container-three" class='container' style="width:100%; height:400px;"></div>

  <div id="container-four" class='container' style="width:100%; height:400px;"></div>

  <div id="container-five" class='container' style="width:100%; height:400px;"></div>

  <div id="container-six" class='container' style="width:100%; height:400px;"></div>

  <div id="container-seven" class='container' style="width:100%; height:400px;"></div>

  <div id="container-eight" class='container' style="width:100%; height:400px;"></div>

  <div id="container-nine" class='container' style="width:100%; height:400px;"></div>

  <div id="container-ten" class='container' style="width:100%; height:400px;"></div>

</div>